default:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://ons-dg-00-dev-stage/athena-results/dev/
      s3_data_dir: s3://ons-dg-00-dev-stage/dbt-data/seeds/dev/
      region_name: us-east-1
      database: AwsDataCatalog        # Catalog (conforme doc da PyPI)
      schema: analytics_dev           # Glue Database
      work_group: primary
      threads: 4
      aws_profile_name: null
      
    prod:
      type: athena
      s3_staging_dir: s3://ons-dg-00-dev-stage/athena-results/prod/
      s3_data_dir: s3://ons-dg-00-dev-stage/dbt-data/seeds/prod/
      region_name: us-east-1
      database: AwsDataCatalog        # Catalog
      schema: analytics_prod          # Glue Database
      work_group: primary
      threads: 8
      aws_profile_name: null
      poll_interval: 1.0
      num_retries: 3